# Generated by Django 4.0.5 on 2022-09-13 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postjob',
            name='price',
        ),
        migrations.RemoveField(
            model_name='postjob',
            name='required_skills',
        ),
    ]
